//
//  Patrols.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.2
//

import Foundation
import UIKit
import AWSDynamoDB

class Patrols: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _time: String?
    var _latitude: NSNumber?
    var _longitude: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "parkingpatrol-mobilehub-426134033-Patrols"
    }
    
    class func hashKeyAttribute() -> String {

        return "_time"
    }
    
    override class func JSONKeyPathsByPropertyKey() -> [NSObject : AnyObject] {
        return [
               "_time" : "time",
               "_latitude" : "latitude",
               "_longitude" : "longitude",
        ]
    }
}
