//
//  UserData.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.2
//

import Foundation
import UIKit
import AWSDynamoDB

class UserData: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _latitudeCar: NSNumber?
    var _longtitudeCar: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "parkingpatrol-mobilehub-426134033-UserData"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    override class func JSONKeyPathsByPropertyKey() -> [NSObject : AnyObject] {
        return [
               "_userId" : "userId",
               "_latitudeCar" : "latitudeCar",
               "_longtitudeCar" : "longtitudeCar",
        ]
    }
}
